Styling/hamburger menu
Svenbjorn/visitfaroeislands.com pull request #158
Opened 2023-10-16 13:39 UTC by BartalD

## Styling of side-menu for Tablet and mobile

### Why?
- VFI wanted the hamburger menu on mobile and tablet to match the design from [Figma](https://www.figma.com/file/eOshLuKuFSfE7gWDYgVcFb/VFI-Tourism---mobile?node-id=0%3A736&mode=dev)

### What has been done?
- I've tried as best as I can to compartmentalize the different segments and use Twig to include them.
  - This was done by extracting the code to different smaller html files.
  - Likewise, the .scss code was extracted into seperate files.
  - This will allow us to use these segments elsewhere, and also makes the code easier to read and edit. Especially main.scss and globals.scss have become highly spaghettified.

- 

#### Details
- Added .svg assets [96efc4265341226d3c6ee9677f8d5f450c3a276c]
- Added media queries from Sendistovan to the Variables file [ed4c3d9b1c12832ee8b2a4fd5f252897cab3ab5b]
  - The plan is that all files will use these dimensions
- Styled the What's On content from the Accordion menu in the side-menu [d8ac160]
- Extracted scss code from global.scss [f1ed2c5]
- Added side menu for mobile/tablet [8cb7ec1]
- Changed What's On accordion from grid to flex [ab1b280]
- Follow Us (Most likely won't be used) [10f4afc]
- Explore the map section [e3ccf55]
- Added 'chosenLanguage' [df96e8c]
- 
## Testing

#### Objective
- To verify that the side-menu styling is consistent and functional across different screen sizes (desktop, tablet, and mobile) in the pull request
- To verify that it matches the syling from [Figma](https://www.figma.com/file/eOshLuKuFSfE7gWDYgVcFb/VFI-Tourism---mobile?node-id=0%3A736&mode=dev)

#### Preconditions
- The pull request with side-menu styling changes is ready for testing
- Make three custom viewports for your browser:
  - Desktop: 1280px and up
  - Tablets: 768px - 1279px
  - Mobile: up to 767px

### Test Procedure:
#### Desktop Testing
- Access the application using a desktop browser.
- Verify that the side-menu styling is visually consistent with the design specifications.
- Check for any layout issues, such as alignment problems or overlapping elements.
- Test the functionality of the side menu, ensuring that it opens and closes smoothly.
- Verify that links and buttons within the side menu are clickable and lead to the correct destinations.

#### Tablet Testing
- Access the application using a tablet-sized viewport (With the dimensions from Sendistovan).
- Verify that the side-menu styling adapts to the tablet screen size gracefully.
- Test the functionality of the side menu, including open and close actions, as well as interactions with menu items.
- Check for any touch-related issues, such as unresponsiveness or overlapping elements.

#### Mobile Testing
- Access the application using a mobile-sized viewport (or use a mobile emulator).
- Verify that the side-menu styling is optimized for mobile screens.
- Test the touch interactions for opening and closing the side menu.
- Check for any issues related to responsiveness, such as text or button size, that may affect usability.
- Verify that the side menu and its content are visually appealing and functional on mobile devices.

2023-10-25 09:39 UTC, Horib commented
Can you link to monday.com task?

2023-10-25 10:03 UTC, Horib requested changes
### Desktop
![firefox_QTKFFJAmal](https://github.com/Svenbjorn/visitfaroeislands.com/assets/25446543/eb566e01-215e-4ab6-8ceb-54b22b545355)


### Tablet & Mobile
![firefox_RBp1bDo9SF](https://github.com/Svenbjorn/visitfaroeislands.com/assets/25446543/280926b9-fa85-4c00-ab99-724c7b61c5a2)
![firefox_gnPnQ3Kk9B](https://github.com/Svenbjorn/visitfaroeislands.com/assets/25446543/8218f1df-8e74-44cd-b0e6-c5c9a5c99c44)
![firefox_06nPeMmGg6](https://github.com/Svenbjorn/visitfaroeislands.com/assets/25446543/006e3b25-6b0f-41bb-b351-7734010133f3)
![firefox_p5PQWGnkts](https://github.com/Svenbjorn/visitfaroeislands.com/assets/25446543/bd3063eb-e3ac-4846-9616-99f8ebdc45e5)
![firefox_CEvrfT3HSS](https://github.com/Svenbjorn/visitfaroeislands.com/assets/25446543/f55b25ba-8165-477f-b1ce-00d0a04c50f4)

### What's On
![firefox_WE1K5m07Vt](https://github.com/Svenbjorn/visitfaroeislands.com/assets/25446543/c0336f76-bea5-4d41-bf1c-15c8cc6bc912)

2023-11-07 14:03 UTC, BartalD commented
# Review-points from Rasmus

### Desktop

- [ ] Menu does not open anymore on desktop
  

### Mobile & Tablet

- [ ] First letter capitalization on the language pane (Figma is not capitalized)
  
- [ ] Scroll overflow problem on menu (was not able to reproduce)
  
- [ ] Missing title for Events, Place etc. (was not able to reproduce)
  
- [ ] Spacing between links (Activities f.x.) (this has to be another pull request, since I need to atomize this large one)
  
- [ ] Missing appearances Image Modules (See & Do) (this has to be another pull request, since I need to atomize this larger one)
  

### All platforms

- [ ] Does not work through VFI

2023-11-16 10:42 UTC, paturvita requested changes
You probably need to delete the font directory and the needsharebutton scripts from the dist folder, these don't look like they belong

There might be a number of files accidentally added, which have been deleted in earlier commits from other people. I've commented on some of them, but might not have caught all.

DESKTOP:

- In the "see & do" menu, we are getting [object object] text on images with missing data. Missing data should be properly handled. This menu point will also link to ...[object object]
![objectobject](https://github.com/Svenbjorn/visitfaroeislands.com/assets/121864791/1c2a9284-b63e-430e-b774-6ad8221cd5fa)

- In the "plan your stay" menu, the currency pane has misaligned elements
![plan your stay](https://github.com/Svenbjorn/visitfaroeislands.com/assets/121864791/7564d924-a27e-4267-8170-3d249d07bf65)

- In the "plan your stay" menu, the good to know pane is echoing out a serialized string. This should be handled properly and maybe the root cause needs to be handled. It is possible that the string is double-serialized and then only unserialized once before being presented.
![goodtoknow](https://github.com/Svenbjorn/visitfaroeislands.com/assets/121864791/1ab4100e-9e02-4029-bbe8-04923fcbf5be)

TABLET:
- The "sites" menu item should be normal font weight
- The "explore the map" menu item should be centered. 
Screendump with both issues:
![sites](https://github.com/Svenbjorn/visitfaroeislands.com/assets/121864791/e5075e61-df74-4e5e-b767-6eb49f6d78f6)

Stopping review, the PR does not match Figma, and there has been some misunderstanding on what was expected in the review as well as what to implement

2023-11-17 12:01 UTC, BartalD commented on assets/Variables/Variables.scss
That is true! But my intent was to give them unique names to distinguish them from any other media queries, such that I, in the future, will have an easier task of cleaning up in them.

2023-11-17 12:04 UTC, BartalD commented on views/menus/sideMenus/mobileTabletSideMenu/style/sideMenu.scss
My intent was to give them unique names to distinguish them from any other media queries, such that I, in the future, will have an easier task of cleaning up in them. The 'VFI' prefix is used such that it is clear that it is the 'official' color-codes, media-queries etc. that VFI have given us from Figma and Invision

2023-11-17 12:06 UTC, BartalD commented on views/modules/social_buttons/social_buttons.html
Not my code. Note to self: Look into this

2023-11-17 12:20 UTC, BartalD commented on git-deploy/deploy.log
[Rasmus](@Horib), do you know what these are for?

2023-11-17 12:20 UTC, BartalD commented on git-deploy/deploy.php
[Rasmus](@Horib), do you know what these are for?

2023-11-17 12:20 UTC, BartalD commented on git-deploy/deployer.php
[Rasmus](@Horib), do you know what these are for?

2023-11-17 12:23 UTC, BartalD commented on views/main/index.html
I have no idea how I have ended up as authoring this code. I don't recognize this.
[Rasmus](@Horib), do you know how this has happened?

2023-11-17 12:27 UTC, BartalD commented on views/modules/social_buttons/social_buttons.html
I have no idea how I have ended up as authoring this code. I don't recognize this.
[Rasmus](@Horib), do you know how this has happened?

2023-11-17 12:32 UTC, BartalD commented
# Pull-Review from [Pætur](@paturvita)

## Unwanted Files

- [ ] Delete font-directory and needsharebutton scripts from Dist-folder
  
- [ ] Delete accidentally added files from previous commits
  

## Desktop

- [ ] [object Object] in See & Do menu
  
  - This bug is live on preview. So it seems that it is a bug from previous commits?
    
- [ ] In the "plan your stay" menu, the currency pane has misaligned elements
  
  - This bug is live on preview. So it seems that it is a bug from previous commits?
    
- [ ] In the "plan your stay" menu, the good to know pane is echoing out a 
  serialized string. This should be handled properly and maybe the root 
  cause needs to be handled. It is possible that the string is 
  double-serialized and then only unserialized once before being 
  presented.
  
  - This bug is live on preview. So it seems that it is a bug from previous commits?
    

## Tablet

- [ ] The "sites" menu item should be normal font weight
  
- [ ] The "explore the map" menu item should be centered.
  
  - This had been fixed. Not sure how it ended up back in the code. But 'explore map' is currently out of scope, so I will delete it.

2023-11-20 11:56 UTC, BartalD commented
[Pætur](@paturvita) and [Rasmus](@Horib), can you re-review this? Regarding the content of the dropdown menus (images and columnization of text), I'm not able to do this at the moment, because the layout of both text and images is user-defined. And therefore I cannot make any general rules for the layout at this moment.

2023-11-21 10:12 UTC, BartalD commented
The submenus now have two columns for tablet. @paturvita and @Horib

2023-11-24 16:28 UTC, paturvita requested changes
Columns in menu are still not acting like they should. Rejecting early instead of going indepth in review

2023-11-28 14:27 UTC, paturvita commented
- Language should not be in all-caps. Image:
![Language](https://github.com/Svenbjorn/visitfaroeislands.com/assets/121864791/0e519200-2131-4245-a9dc-b9e17bb5a5d9)
- Overflow does not include the "sites" menu item. To reproduce, expand some menu item so that the menu overflows its container and observe that "sites" disappears from the menu. screenshot:
![overflow](https://github.com/Svenbjorn/visitfaroeislands.com/assets/121864791/178f5bf0-fd7b-4f49-b04a-817b77ab8f41)
- Menu items are not spaced as in Figma. Difficult to give perfect pixel values, but the difference is visually apparent.
![line height](https://github.com/Svenbjorn/visitfaroeislands.com/assets/121864791/9482e040-2706-4781-b10e-83367024f623)
- Spacing between icon and text is not the same as in Figma. Screenshot
![whatson menu](https://github.com/Svenbjorn/visitfaroeislands.com/assets/121864791/d0b15be2-cdc8-4fe1-8be9-1f72547a1284)
- Language list is not aligned as in Figma. Languages should be aligned to same vertical line as the menu point headers.
![Languages](https://github.com/Svenbjorn/visitfaroeislands.com/assets/121864791/6917d09f-cb8a-45e6-af0a-437844daecfd)
- In tablet, the whatson menu points are not shown in the same vertical ratio as Figma (portrait-like ratio) see img below
- In tablet, whatson menu points contain additional text not shown in figma. see img
![whatsonimgs](https://github.com/Svenbjorn/visitfaroeislands.com/assets/121864791/4b5768ef-c1ed-41d9-a544-6c0e4794a491)

2023-11-29 16:50 UTC, BartalD commented
# Fixes from Pull-Review from [Pætur](@paturvita)
- [x] Language should not be in all-caps
  
- [x] Overflow does not include the "sites" menu item
  
- [x] Menu items are not spaced as in Figma
  
- [x] Spacing between icon and text is not the same as in Figma
  
- [x] Language list is not aligned as in Figma
  
- [x] In tablet, the whatson menu points are not shown in the same vertical ratio as Figma (portrait-like ratio)
  
- [x] In tablet, whatson menu points contain additional text not shown in figma

2023-11-30 08:56 UTC, merged